### ISSUE TITLE
Getting TypeScript Compilation error on the console while executing the test scenario

### ISSUE THREAD

**Issue by mailtogagan** [Tallyb/cucumber-playwright#175]
Getting TypeScript Compilation error on the console while executing the test scenario using the `cucumber-playwright` template. However scenarios are getting executed successfully.

Steps to reproduce:
1. Use the `cucumber-playwright` template to create my repo on GitHub.
2. Clone my repo on local machine.
2. Install the dependencies using `npm i`
3. Execute the scenario using `npm run test`

P.S. - Using VSCode for execution.

```
PS C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example> npx cucumber-js
TSError: ⨯ Unable to compile TypeScript:
src/support/custom-world.ts:2:10 - error TS2305: Module '"@cucumber/messages"' has no exported member 'messages'.

2 import { messages } from '@cucumber/messages';
           ~~~~~~~~

    at createTSError (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\ts-node\src\index.ts:618:12)     
    at reportTSError (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\ts-node\src\index.ts:622:19)     
    at getOutput (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\ts-node\src\index.ts:809:36)
    at Object.compile (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\ts-node\src\index.ts:1111:30)   
    at Module.m._compile (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\ts-node\src\index.ts:1224:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\ts-node\src\index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\@cucumber\cucumber\src\cli\index.ts:166:9
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\@cucumber\cucumber\src\cli\index.ts:164:22)
    at Cli.run (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\@cucumber\cucumber\src\cli\index.ts:190:37)
    at Object.run [as default] (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\node_modules\@cucumber\cucumber\src\cli\run.ts:24:14)
codepath: C:\Users\meet_\OneDrive\Desktop\Work\Playwright\GitHub\cucumber-playwright-example\src\support\custom-world.ts
@foo
Feature: Playwright docs # features\playwright.feature:2

  @foo
  Scenario: Change theme # features\playwright.feature:7
    Given Go to the playwright website
    When Change theme to "light" mode
    Then Snapshot
    When Change theme to "dark" mode
    Then Snapshot

1 scenario (1 passed)
5 steps (5 passed)
0m05.300s (executing steps: 0m04.994s)
```

**Comment by lakshmanp21** [comment]
same issue encountered, 7.2.1 version is working

**Comment by Tallyb** [comment]
Fixed with https://github.com/Tallyb/cucumber-playwright/commit/b1866bcce7b207966d2c43715cc58b454c9d67bc
