### ISSUE TITLE
allure report issue "Unrecognized extension: text/x.cucumber.log+plain"

### ISSUE THREAD

**Issue by jzaratei** [Tallyb/cucumber-playwright#647]
Hello!
I'm getting this error when I try to generate the allure report with attachments:

Error: Unrecognized extension: text/x.cucumber.log+plain
    at typeToExtension (/home/user/Documentos/projects/framework-base/node_modules/allure-js-commons/src/writers/utils.ts:35:9)
    at buildAttachmentFileName (/home/user/Documentos/projects/framework-base/node_modules/allure-js-commons/src/AllureRuntime.ts:12:36)
    at AllureRuntime.writeAttachment (/home/user/Documentos/projects/framework-base/node_modules/allure-js-commons/src/AllureRuntime.ts:46:22)
    at CucumberJSAllureFormatter.onAttachment (/home/user/Documentos/projects/framework-base/node_modules/allure-cucumberjs/src/CucumberJSAllureReporter.ts:383:51)
    at CucumberJSAllureFormatter.parseEnvelope (/home/user/Documentos/projects/framework-base/node_modules/allure-cucumberjs/src/CucumberJSAllureReporter.ts:172:12)
    at EventEmitter.emit (node:events:524:35)
    at EventEmitter.emit (node:domain:489:12)

Code:
```
When('I request the descContent service', async function (this: ICustomWorld) {
  const dataPayload = fs.readFileSync('test_data/hotelContent.xml', 'utf8');
  this.attach(dataPayload, 'application/xml');
  this.response = await this.server?.post('/my-masterdata-ws', {
    headers: {
      'content-type': 'application/soap+xml;charset=utf-8',
    },
    data: dataPayload,
  });
});
```

Do you have any idea what would be the cause of this issue?

Thanks for your support!

**Comment by Tallyb** [comment]
did you find a solution?

**Comment by jzaratei** [comment]
Not really. It probably was a dependency versioning issue, cause I did a fresh install and all seems to work fine.
